apiVersion: v1
kind: Service
metadata:
  name: worker-service
  namespace: vote-app
spec:
  type: ClusterIP
  selector:
    app: vote-app
    component: worker
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: worker-ingress
  namespace: vote-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: worker.local
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: worker-service
                port:
                  number: 80            